version: "3"
services:
  react-app:
    image: sm-react-app-dev
    stdin_open: true
    
#tty and stdin_open are analogous to the -t and -i arguments for the docker run command, respectively.
#You use stdin_open when you need to work on a project outside the Docker container. 
#You use tty when you need to work on a project inside the Docker container
    ports:
      - "8000:8000"
    networks:
      - sm-app
      
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
  sm-server:
    image: sm-server
    ports:
      - "3000:3000"
    networks:
      - sm-app
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - sm-app
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local
    
networks:
  sm-app:
    driver: bridge
