version: "3"
services:
  react-app:
    image: sm-react-app-dev
    stdin_open: true
    ports:
      - "8000:8000"
    networks:
      - sm-app
      
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
  sm-server:
    image: sm-server
    ports:
      - "3000:3000"
    networks:
      - sm-app
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - sm-app
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local
    
networks:
  sm-app:
    driver: bridge